services: 
  web: 
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes: 
      - ./backend/djangobnb/:/usr/src/djangobnb/
    ports:
      - 8001:8000
    env_file:
      - ./backend/.docker_env.dev
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    environment:
      - POSTGRES_USER=rk
      - POSTGRES_PASSWORD=rk_123456
      - POSTGRES_DB=djangobnb
    
volumes:
  postgres_data: 
